#load @"Microsoft.CSharp.fsx" 
#load @"NETStandard.Library.fsx" 
#load @"System.ComponentModel.TypeConverter.fsx" 
#load @"System.Runtime.Serialization.Formatters.fsx" 
#load @"System.Runtime.Serialization.Primitives.fsx" 
#load @"System.Xml.XmlDocument.fsx" 
#r "../../../../../../.nuget/packages/newtonsoft.json/10.0.3/lib/net45/Newtonsoft.Json.dll" 