#load @"System.Collections.fsx" 
#load @"System.Reflection.fsx" 
#load @"System.Resources.ResourceManager.fsx" 
#load @"System.Runtime.fsx" 
#load @"System.Runtime.Serialization.Primitives.fsx" 
#r "../../../../../../.nuget/packages/system.runtime.serialization.formatters/4.3.0/lib/net46/System.Runtime.Serialization.Formatters.dll" 