#load @"System.Diagnostics.Debug.fsx" 
#load @"System.Globalization.fsx" 
#load @"System.Resources.ResourceManager.fsx" 
#load @"System.Runtime.fsx" 
#load @"System.Runtime.Extensions.fsx" 
#load @"System.Threading.fsx" 
#r "System" 
#r "../../../../../../.nuget/packages/system.collections.nongeneric/4.3.0/lib/net46/System.Collections.NonGeneric.dll" 