#load @"System.IO.fsx" 
#load @"System.Net.Primitives.fsx" 
#load @"System.Runtime.fsx" 
#load @"System.Threading.Tasks.fsx" 
#r "System" 
#r "../../../../../../.nuget/packages/system.net.sockets/4.3.0/lib/net46/System.Net.Sockets.dll" 