#load @"Fable.Core.fsx" 
#load @"Fable.Elmish.fsx" 
#load @"Fable.PowerPack.fsx" 
#load @"Fable.React.fsx" 
#r "../../../../../../.nuget/packages/fable.elmish.react/1.0.1/lib/netstandard1.6/Fable.Elmish.React.dll" 