#load @"Fable.Core.fsx" 
#load @"Fable.Elmish.fsx" 
#load @"Fable.PowerPack.fsx" 
#load @"Fable.React.fsx" 
#r "../../../../../../.nuget/packages/fable.elmish.react/2.0.0-beta-4/lib/netstandard2.0/Fable.Elmish.React.dll" 